<?php
$tokens = 
[
    0 => [
        '_type' => 'token',
        'tipo' => 'apoio',
        'nome' => '',
        'ativo' => 0,
        'token' => 'TJTQVE',
    ],
    1 => [
        '_type' => 'token',
        'tipo' => 'painel',
        'nome' => '',
        'ativo' => 0,
        'token' => 'AKPIEU',
    ],
    2 => [
        '_type' => 'token',
        'tipo' => 'recepcao',
        'nome' => '',
        'ativo' => 0,
        'token' => 'FKVUCI',
    ],
    3 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'DYFIAN',
    ],
    4 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'ARBSNW',
    ],
    5 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'UMJQFN',
    ],
    6 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'YSCNTU',
    ],
    7 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'GLDJMY',
    ],
    8 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'ZVGTUB',
    ],
    9 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'AKCYIT',
    ],
    10 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'NCRQIQ',
    ],
    11 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'WOTYZJ',
    ],
    12 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'CWHUUP',
    ],
    13 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'VYZDSY',
    ],
    14 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'KZECPY',
    ],
    15 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'UODTYW',
    ],
    16 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'JLRQZY',
    ],
    17 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'YMKWXH',
    ],
    18 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'XZACSE',
    ],
    19 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'RJAJXM',
    ],
];
