<?php
    $tokens = 
    [
    0 => [
        '_type' => 'token',
        'tipo' => 'apoio',
        'nome' => '',
        'ativo' => 0,
        'token' => 'MVJUYX',
    ],
    1 => [
        '_type' => 'token',
        'tipo' => 'painel',
        'nome' => '',
        'ativo' => 0,
        'token' => 'NLYAHZ',
    ],
    2 => [
        '_type' => 'token',
        'tipo' => 'recepcao',
        'nome' => '',
        'ativo' => 0,
        'token' => 'HQWEXB',
    ],
    3 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'QIZDHX',
    ],
    4 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'DQWUGP',
    ],
    5 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'FAXJCQ',
    ],
    6 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'YJPFFN',
    ],
    7 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'TEPNSF',
    ],
    8 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'NDQRDT',
    ],
    9 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'XINSMN',
    ],
    10 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'TUHAYY',
    ],
    11 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'GPWTTZ',
    ],
    12 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'BPOVMZ',
    ],
    13 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'GGDNVY',
    ],
    14 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'AWQDFN',
    ],
    15 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'SZDJHM',
    ],
    16 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'TOTELO',
    ],
    17 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'HUELFM',
    ],
    18 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'ZHVDJU',
    ],
    19 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'FMAJIE',
    ],
    20 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'PFUJDW',
    ],
    21 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'TVUGTJ',
    ],
    22 => [
        '_type' => 'token',
        'tipo' => 'fechada',
        'nome' => '',
        'ativo' => 0,
        'token' => 'FIGRXH',
    ],
    23 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'DERNKP',
    ],
    24 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'VTESHM',
    ],
    25 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'FTGYSU',
    ],
    26 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'BCRFYV',
    ],
    27 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'AZEBUC',
    ],
    28 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'QUFYXA',
    ],
    29 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'RTQXGY',
    ],
    30 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'OBBVMV',
    ],
    31 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'VYMCBE',
    ],
    32 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'RKWSAW',
    ],
    33 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'ABWKIV',
    ],
    34 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'RHUPNH',
    ],
    35 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'HFEBEU',
    ],
    36 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'JOIOYG',
    ],
    37 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'IQKDVS',
    ],
    38 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'CQBNBS',
    ],
    39 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'YADBNL',
    ],
    40 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'MBYTSG',
    ],
    41 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'VLVEFS',
    ],
    42 => [
        '_type' => 'token',
        'tipo' => 'aberta',
        'nome' => '',
        'ativo' => 0,
        'token' => 'RZPCMN',
    ],
];
    